CREATE TABLE IF NOT EXISTS dnf_service.gm_operation_audit (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    request_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    operator_uid BIGINT UNSIGNED NOT NULL,
    operator_name VARCHAR(120) NOT NULL DEFAULT '',
    client_ip VARCHAR(45) NOT NULL DEFAULT '',
    module VARCHAR(64) NOT NULL,
    action VARCHAR(64) NOT NULL,
    target_account_id BIGINT UNSIGNED NULL,
    target_charac_no INT UNSIGNED NULL,
    request_json LONGTEXT NULL,
    before_json LONGTEXT NULL,
    after_json LONGTEXT NULL,
    response_json LONGTEXT NULL,
    status VARCHAR(16) NOT NULL,
    sync_status VARCHAR(32) NULL,
    message VARCHAR(1000) NULL,
    created_at DATETIME NOT NULL,
    completed_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_gm_operation_audit_request (request_id),
    KEY idx_gm_operation_audit_account_time (target_account_id, created_at),
    KEY idx_gm_operation_audit_charac_time (target_charac_no, created_at),
    KEY idx_gm_operation_audit_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
